---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-sync
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-sync
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
