apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - source.yaml
  - prometheus
  - loki
configMapGenerator:
  - name: monitoring-values
    files:
      - values-loki.yaml=loki/values.yaml
      - values-prometheus.yaml=prometheus/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
