---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./clusters/kind-cluster/monitoring/prometheus/instance
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
