grafana:
  ingress:
    enabled: true
    hosts:
    - monitoring.dsch-l3.com
    ingressClassName: nginx-monitoring
  additionalDataSources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
    editable: false
    isDefault: false
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true
